import { Search, Book, Users, FileText, Briefcase, Wallet, Megaphone, FolderOpen, Settings, Sparkles, Send, ClipboardList, CheckCircle2, LayoutGrid, Package, RefreshCw, Zap, Check } from "lucide-react";
import type { LucideIcon } from "lucide-react";

export interface DocSection {
  id: string;
  title: string;
  icon: React.ReactNode;
  category: string;
  content: {
    apa: string;
    cara: string[];
    fitur: string[];
    tips?: string[];
    faq?: { q: string; a: string }[];
  };
}

export const CATEGORIES = ["Mulai", "Akuisisi Leads", "Sales", "Klien", "Delivery", "Operasional", "Marketing", "AI Tools", "Dokumen", "Master Data", "System"];

export const SECTIONS: DocSection[] = [
  { id: "login", title: "Login & Akun", category: "Mulai", icon: <Users size={16} />, content: { apa: "Halaman masuk ke sistem CRM. Setiap user punya akun sendiri dengan role admin atau member.", cara: ["Buka halaman login", "Masukkan email dan password", "Klik tombol Masuk", "Sistem akan redirect ke Dashboard"], fitur: ["Auto-redirect kalau sudah login", "Logo brand kit otomatis tampil", "Cookie HttpOnly untuk keamanan", "Rate limit 5x percobaan / 5 menit"], tips: ["Lupa password? Hubungi admin untuk reset.", "Jangan share akun — setiap action tercatat di Audit Log."] } },
  { id: "dashboard", title: "Dashboard", category: "Mulai", icon: <Book size={16} />, content: { apa: "Halaman utama yang menampilkan ringkasan bisnis: total leads, klien aktif, conversion rate, dan hot leads.", cara: ["Login → otomatis ke Dashboard", "Lihat 4 stat cards di atas", "Hot Leads = lead yang baru lihat proposal dalam 24 jam", "Top Scored = lead dengan score AI tertinggi"], fitur: ["Auto-refresh setiap 60 detik", "Re-engagement alerts untuk lead yang hampir hilang", "Bar chart distribusi leads per produk"] } },
  { id: "sop-workflow", title: "SOP Workflow Bisnis", category: "Mulai", icon: <ClipboardList size={16} />, content: { apa: "Alur kerja utama dari cari prospek sampai proyek selesai. SOP ini jadi pegangan agar tim tidak bingung kapan pakai Leads, Report, Proposal, Board, Workspace, Dokumen, dan Invoice.", cara: ["Akuisisi: AI Scrape/Maps Scraper → lead tersimpan dengan batch", "Kualifikasi: scoring otomatis + scoring manual jika perlu", "Outreach: pilih batch → filter score/status → WA Blast berisi link report", "Engagement: lead buka report → durasi baca dan aktivitas tercatat → score naik", "Sales: follow-up → buat proposal dari lead/klien/halaman proposal", "Deal: proposal accepted/manual deal → project, board, workspace, dokumen resmi, dan notifikasi dibuat", "Delivery: Board untuk progress visual, Workspace untuk SOP data kerja dan bukti output", "Finance: invoice DP/termin/bulanan dibuat dari project dan dokumen masuk arsip klien"], fitur: ["Report fallback tetap bisa dibuat walau AI analysis scrape belum ada", "Scoring bisa otomatis dan dapat disesuaikan manual", "Proposal PDF sebelum deal, MoU/kontrak/invoice setelah deal", "Notifikasi sistem untuk aksi otomatis", "Audit Log mencatat aksi user"], tips: ["Cold lead sebaiknya dikirimi report dulu agar terasa diperhatikan.", "Warm lead atau yang sudah balas bisa langsung proposal.", "Board bukan spreadsheet; Board untuk status eksekusi, Workspace untuk detail SOP, link bukti, PIC, dan kriteria selesai."] } },
  { id: "scraper", title: "Maps Scraper", category: "Akuisisi Leads", icon: <Search size={16} />, content: { apa: "Tool untuk scrape bisnis dari Google Maps berdasarkan kategori dan lokasi. Hasil otomatis tersimpan sebagai leads.", cara: ["Klik menu Maps Scraper di sidebar", "Isi kategori (contoh: 'restoran'), lokasi ('Jakarta Selatan'), dan max results", "Pilih product interest yang relevan", "Klik Scrape — leads akan masuk ke /contacts dengan rating Google", "AI Analysis aktif → tiap lead dapat pain points dan suggested product"], fitur: ["Source: Google Places API (data resmi)", "Auto-deduplication berdasarkan phone number", "Batch name untuk grouping hasil scrape", "Riwayat scrape tersimpan dengan filter tanggal", "Concurrent limit untuk hindari rate limit"], tips: ["Pakai kata kunci spesifik agar hasil relevan.", "Max 100 results per scrape — split kalau perlu lebih.", "Jangan scrape kategori yang sama dua kali — bakal duplicate.", "AI Analysis butuh AI provider configured di Settings → AI Engine."] } },
  { id: "leads", title: "Leads & Prospek", category: "Akuisisi Leads", icon: <Users size={16} />, content: { apa: "Daftar semua bisnis yang sudah di-scrape atau ditambahkan manual. Status leads dari Scraped → Contacted → Replied → Closed.", cara: ["Buka /contacts", "Filter berdasarkan status, batch, rating, atau score", "Klik nama bisnis untuk detail", "Update status manual atau lewat WA reply", "Klik Convert untuk jadikan klien (Contact) — wajib sebelum buat proposal"], fitur: ["Lead score AI: Siap Closing (≥80), Perlu Pendekatan (50-79), Belum Match (<50)", "Tracking proposal views — lead yang buka proposal terdeteksi di Dashboard (Hot Leads)", "Bulk filter dan export CSV", "Map view untuk lihat sebaran geografis", "Soft-delete dengan restore button"], tips: ["Score ≥80 (Siap Closing) = prioritas convert dan follow-up.", "Status Contacted otomatis update saat blast WA terkirim.", "Lead archived 30+ hari bisa di-purge admin.", "Pastikan AI provider sudah dikonfigurasi di Settings agar AI Analysis aktif saat scrape."] } },
  { id: "proposals", title: "Proposal", category: "Sales", icon: <FileText size={16} />, content: { apa: "Buat dan kirim proposal ke klien. Klien bisa accept/reject langsung dari link publik. Proposal accepted otomatis bikin Project + Board + Workspace.", cara: ["Convert lead dulu di /contacts → klien muncul di /clients", "Buka /clients → klik aksi pada klien → Buat Proposal", "Pilih services dan addons", "Set timeline (auto-generate dari template)", "Sistem hitung total + diskon (configurable di Settings)", "Copy link /p/{slug} → kirim ke klien via WA", "Klien klik Accept → admin dapat notifikasi WA, Project + Board + Workspace auto-created"], fitur: ["Tracking pixel: tahu kapan klien buka proposal + durasi baca", "Discount countdown 24 jam", "FAQ otomatis (configurable)", "Social proof (jumlah klien yang sudah pakai)", "Public OG image untuk preview di WhatsApp", "Workspace auto-init hanya jika service_type punya template (web_dev, seo_gmaps, sosmed, dll)", "Soft-delete + restore"], tips: ["Pakai timeline template SEO/web/sosmed sesuai service.", "Diskon dan FAQ default bisa diubah di Settings → AI Engine.", "Track view duration di /proposals untuk lihat keseriusan klien."] } },
  { id: "report", title: "Laporan Digital (Audit Report)", category: "Sales", icon: <FileText size={16} />, content: { apa: "Laporan audit digital untuk bisnis lokal. Dipakai sebagai pemikat sebelum kirim proposal.", cara: ["Dari detail lead → Generate Report", "Jika AI analysis tersedia: sistem pakai pain points, saran produk, dan hasil analisis", "Jika AI analysis belum ada: report tetap dibuat dari nama bisnis, kategori, kota, estimasi pencarian, dan pembanding lead sejenis", "Copy link /r/{slug} → kirim ke target", "Target lihat report → durasi baca dan aktivitas tercatat"], fitur: ["Competitor count berdasarkan lead sejenis dari kategori + kota", "Monthly search volume estimate", "Fallback copy yang jujur saat AI analysis scrape kosong", "Pricing dengan discount timer", "City/province map", "Bot-aware OG meta tags untuk preview WhatsApp"], tips: ["Kapan pakai Audit Report? Cold lead atau lead yang baru kenal — kasih hook value dulu sebelum kirim proposal.", "Lead Replied/Warm → langsung Proposal, skip Audit Report.", "Setelah target buka report, lead score otomatis naik sebagai engagement signal."] } },
  { id: "clients", title: "Klien (Buku Klien)", category: "Klien", icon: <Users size={16} />, content: { apa: "Daftar klien aktif yang sudah convert dari leads. Track LTV, billing aktif, dana talangan, dan project ongoing.", cara: ["Buka /clients", "Klik klien untuk detail", "Tambah project (FIXED atau RETAINER)", "Catat notes per kategori (Bisnis/Teknis/Penting)", "Simpan kredensial klien (terenkripsi)", "Tambah link dokumen cloud"], fitur: ["LTV calculator (FIXED + RETAINER × bulan)", "Active billing total", "Dana talangan = pengeluaran belum di-billing", "Notes timeline dengan filter kategori", "Credentials vault terenkripsi (Fernet)"], tips: ["Retainer dihitung nominal × bulan jalan.", "Tag transaksi dengan client_id di /finance untuk track dana talangan.", "Dana talangan hilang setelah invoice digenerate yang reference transaksi tersebut.", "Kredensial otomatis encrypt saat simpan."] } },
  { id: "board", title: "Project Board (Kanban)", category: "Delivery", icon: <Briefcase size={16} />, content: { apa: "Kanban untuk melihat status kerja secara cepat. Board menjawab pertanyaan: task mana yang To Do, In Progress, Review, Done.", cara: ["Buka /board", "Pilih project → board terbuka", "Tambah card di kolom To Do", "Drag card ke In Progress / Review / Done", "Klik card → tambah komentar, checklist, due date, attachment, dan lihat log aktivitas"], fitur: ["4 default columns: To Do, In Progress, Review, Done", "Card bisa linked ke workspace row untuk 2-way sync", "Activity log per card", "Archive board untuk simpan, restore kapan saja", "Label warna hanya untuk tag card agar board tidak terlalu ramai"], tips: ["Board bukan tempat data detail kerja; pakai Workspace untuk SOP, output, dan link bukti.", "Card yang linked ke workspace sebaiknya judulnya diubah dari Workspace agar data sinkron."] } },
  { id: "workspace", title: "Workspace (Spreadsheet)", category: "Delivery", icon: <Briefcase size={16} />, content: { apa: "Workspace adalah spreadsheet operasional per project. Ini pengganti sheet lama: berisi SOP layanan, PIC, deadline, link bukti, kriteria selesai, dan tracker per layanan.", cara: ["Project dibuat → workspace auto-init dari template service_type", "Buka /workspace → pilih project", "Isi status, PIC, deadline, output/link bukti, dan catatan", "Checklist Selesai → status otomatis Done dan card Board ikut pindah Done", "Untuk SEO/GMB, gunakan sheet Keyword Tracker, Artikel Tracker, dan Google Business Tracker"], fitur: ["Service templates SOP: web_dev, seo_gmaps, sosmed, maintenance, web_dev_bulanan, branding, general", "Multi-sheet per bulan untuk retainer", "Custom column types (text, number, date, select, checkbox, url)", "Attachment upload per row", "Auto-prompt invoice saat task 'Invoice pembayaran X%' di-mark Done"], tips: ["Board = peta status visual. Workspace = data kerja detail dan bukti output.", "Project selesai setelah semua task penting Done, invoice lunas, dokumen final rapi, lalu admin klik selesai/arsip.", "Jangan hapus row template kalau masih dipakai tim sebagai SOP."] } },
  { id: "finance", title: "Keuangan", category: "Operasional", icon: <Wallet size={16} />, content: { apa: "Multi-wallet finance tracker. Catat income/expense, hitung BEP, financial runway, dan track outreach cost.", cara: ["Buka /finance", "Tambah wallet (Bank, E-wallet, Cash)", "Catat transaksi (income/expense + kategori)", "Tag transaksi dengan klien untuk dana talangan", "Lihat reports: balance, BEP, runway"], fitur: ["Auto wallet balance update", "Soft-delete + restore transaksi", "Export CSV", "Outreach cost analytics (CPA, ROI per campaign)", "Provider quota tracking (Fonnte, AI)"], tips: ["BEP = total expense bulanan — perlu revenue minimal sebanyak ini.", "Runway = balance ÷ pengeluaran bulanan, dalam bulan."] } },
  { id: "subscriptions", title: "Langganan (Subscriptions)", category: "Operasional", icon: <Wallet size={16} />, content: { apa: "Track recurring expenses bulanan/tahunan. Klik tombol tiap awal bulan untuk catat pengeluaran otomatis ke wallet.", cara: ["Buka /finance/subscriptions", "Tambah langganan (nama, jumlah, billing cycle, next date)", "Tiap awal bulan → klik 'Catat Pengeluaran Bulan Ini'", "Sistem buat expense transaction + update next billing date"], fitur: ["Billing cycle: monthly, yearly, weekly, daily", "Days-until countdown", "One-click batch deduct semua yang jatuh tempo"] } },
  { id: "blast", title: "WA Blast", category: "Marketing", icon: <Megaphone size={16} />, content: { apa: "Kirim WhatsApp massal ke leads via Fonnte API. Track delivery, read, reply, dan conversion funnel.", cara: ["Filter leads di /contacts (status, batch, product)", "Klik Blast → pilih template", "Set jadwal atau kirim sekarang", "Monitor di /marketing/blast-analytics"], fitur: ["Funnel tracking: Sent → Delivered → Read → Replied → Closed", "Per-template performance stats", "Webhook auto-update status saat klien reply", "Schedule blast via APScheduler", "Cost tracking per campaign"], tips: ["Pakai variable {{business_name}}, {{client_name}} di template.", "Reply rate >5% sudah bagus untuk cold outreach.", "Jangan blast >100 nomor sekaligus — risk WA banned."] } },
  { id: "followup", title: "Follow-up Otomatis", category: "Marketing", icon: <Megaphone size={16} />, content: { apa: "Sequence pesan otomatis ke leads yang belum reply. Sistem auto-stop kalau lead sudah reply.", cara: ["Dari detail lead → Start Follow-up", "Pilih template_ids urut (3 step default)", "Set delays (contoh: [1, 3, 7] hari)", "Sistem kirim otomatis tiap 30 menit (cron)"], fitur: ["Auto-stop kalau lead sudah reply (cek BlastMessage.replied_at)", "Multi-step sequence (max 7 steps)"], tips: ["Sequence tidak bisa di-resume setelah di-stop — start ulang dari detail lead jika perlu.", "Cron jalan tiap 30 menit — pesan tidak langsung terkirim saat jadwal."] } },
  { id: "ads", title: "Iklan & Kampanye", category: "Marketing", icon: <Megaphone size={16} />, content: { apa: "Track campaign iklan berbayar (Meta Ads, Google Ads). Status PLANNING → ACTIVE → COMPLETED.", cara: ["Buka /marketing/ads", "Tambah campaign (nama, target audience, budget, drive link)", "Set status ACTIVE → expense otomatis tercatat di wallet 'Dompet Budget Ads'", "Update leads_count + conversions_count manual"], fitur: ["Auto-create wallet 'Dompet Budget Ads'", "CPA dan cost per lead calculator", "Drive link untuk kreatif materials"] } },
  { id: "calendar", title: "Kalender Konten", category: "Marketing", icon: <Megaphone size={16} />, content: { apa: "Schedule konten sosial media bulanan. Optional sync ke Google Calendar.", cara: ["Buka /marketing/calendar", "Klik tanggal → tambah konten", "Pilih type: IG Carousel, Reels, SEO Article, TikTok, YouTube", "Status: DRAFT → SCHEDULED → PUBLISHED"], fitur: ["Custom content types dengan color labels", "Google Calendar sync (perlu setup di Settings)", "Monthly view dengan drag-drop"] } },
  { id: "content-generator", title: "Generator Konten (AI)", category: "AI Tools", icon: <Sparkles size={16} />, content: { apa: "Generate Artikel SEO dengan AI. Modul ini sengaja dibuat fokus ke artikel SEO agar workflow konten tidak bercampur dengan fitur gambar/caption.", cara: ["Buka /content-generator", "Buat session baru atau pilih session yang sudah ada", "Isi keyword utama, intent, brief, target pembaca, dan struktur artikel", "Klik Generate Artikel SEO", "Review hasil dan publish ke CMS jika sudah siap"], fitur: ["SEO Article: search intent, outline, LSI keywords, FAQ, meta title/description", "Session context membawa riwayat generation sebelumnya", "Publish article ke CMS langsung", "Markdown rendering inline"], tips: ["Atur provider/model di Settings → AI Engine.", "Pakai session berbeda untuk tiap klien atau topik besar.", "Tetap review manual sebelum publish agar tone dan fakta sesuai."] } },
  { id: "ai-chat", title: "AI Chat (Asisten Bisnis)", category: "AI Tools", icon: <Sparkles size={16} />, content: { apa: "AI assistant untuk diskusi bisnis. Bisa query data CRM langsung (RAG), tool calling, dan persistent memory.", cara: ["Buka /chat", "Buat project baru (kasih system prompt)", "Pilih model dari dropdown", "Mulai chat — AI bisa akses leads, transactions, dll", "Pin pesan penting jadi memory"], fitur: ["Multi-project, multi-conversation", "RAG: AI auto-query DB tables relevant", "Tool calling: create_lead, search_leads, send_whatsapp, etc", "Memory persists across conversations", "Auto-summarization tiap 10 messages", "Fullscreen toggle"], tips: ["AI bisa kirim WA otomatis via tool send_whatsapp — review prompt dan pastikan konteks benar sebelum aktifkan.", "Pakai project terpisah untuk topik berbeda agar memory tidak tercampur."] } },
  { id: "documents", title: "Dokumen & Arsip", category: "Dokumen", icon: <FolderOpen size={16} />, content: { apa: "Foldering system untuk simpan notes dan link dokumen. Mirip Notion lite.", cara: ["Buka /documents", "Buat folder dengan warna", "Tambah dokumen (notes atau external URL)", "Tag untuk searchability"], fitur: ["Nested folders dengan colored labels", "Rich text body atau external URL", "Search across all docs", "Tags untuk grouping"] } },
  { id: "doc-generator", title: "Generator Dokumen (Invoice, Kontrak)", category: "Dokumen", icon: <FileText size={16} />, content: { apa: "Generate PDF dari template HTML. Untuk invoice, proposal PDF, kontrak, surat penawaran.", cara: ["Buka /documents/generator → New", "Step 1: Pilih template", "Step 2: Pilih target (klien atau kosong)", "Step 3: Isi variables", "Step 4: Preview", "Step 5: Done — download atau email"], fitur: ["Template types: invoice, proposal_pdf, kontrak, surat_penawaran, custom", "Brand kit auto-injected (logo, colors, fonts)", "Tracking pixel embedded — tahu kapan dibuka", "Email delivery via SMTP", "Jinja2 templating"] } },
  { id: "brand-kit", title: "Brand Kit", category: "Master Data", icon: <Settings size={16} />, content: { apa: "Single source of truth untuk identitas brand: logos, warna, font, tagline.", cara: ["Buka /master/brand-kit (admin only)", "Upload logo primary, secondary, brandmark", "Tambah warna palette", "Set font + tagline"], fitur: ["Logo otomatis tampil di Sidebar, Login, PWA icon", "Brandmark = favicon", "Allowed: PNG, JPG, JPEG, WEBP, ICO, SVG", "Max 2MB per file", "Public endpoint /api/brand-kit/public (no auth)"] } },
  { id: "master-data", title: "Data Master (Produk, Kategori, Template)", category: "Master Data", icon: <Settings size={16} />, content: { apa: "Konfigurasi produk yang dijual, kategori, dan template pesan.", cara: ["/master/products — katalog layanan/produk", "/master/categories — grouping produk", "/master/templates — template pesan WA Blast, Proposal, Follow-up"], fitur: ["Product types: FIXED atau RETAINER", "ROI calculator per produk (months, multiplier)", "Template variables: {{client_name}}, {{business_name}}, etc", "Per-template stats: reply rate, conversion rate"] } },
  { id: "vault", title: "Brankas Internal", category: "Master Data", icon: <Settings size={16} />, content: { apa: "Vault terenkripsi untuk simpan kredensial internal (API keys, passwords, tokens) yang BUKAN milik klien.", cara: ["Buka /master/internal-vault", "Tambah credential (kategori, title, fields)", "Mark field sebagai secret → encrypted di DB", "Copy value dengan satu klik"], fitur: ["Fernet encryption (AES symmetric)", "Categories: WordPress, Google, Server, Email, etc", "Field-level secret toggle", "Show/hide values"], tips: ["Jangan share screenshot — copy via tombol Copy.", "Kredensial klien simpan di /clients, bukan di sini."] } },
  { id: "costs", title: "Biaya & Kuota", category: "Marketing", icon: <Wallet size={16} />, content: { apa: "Dashboard untuk monitor sisa kuota provider (Fonnte, AI) dan estimate balance bulanan.", cara: ["Buka /marketing/costs", "Lihat remaining quota Fonnte, Gemini, Claude, OpenAI", "Top-up quota saat habis", "Reset error status setelah top-up"], fitur: ["Per-campaign operational cost", "ROI dan CPA per campaign", "Provider configs editable"] } },
  { id: "settings", title: "Pengaturan & Integrasi", category: "System", icon: <Settings size={16} />, content: { apa: "Konfigurasi global sistem: profil user, tim & role, AI provider, integrasi (Fonnte, Google, SMTP), audit logs, dan data admin.", cara: ["Buka /settings", "Tab Profil: ganti nama dan password", "Tab Tim & Role: buat akun tim, ubah role, reset password", "Tab AI Engine: konfigurasi base URL, API key, dan model", "Tab Integrasi: Fonnte token, Google API, SMTP, follow-up schedule", "Tab Audit Logs: riwayat aksi user", "Tab Data: backup, seed, reset sesuai kebutuhan admin"], fitur: ["HCM MVP: create/update/delete user role admin/member", "Multi-provider AI sederhana dari base URL/API key/model", "External lead API key untuk webhook", "Auto follow-up schedule (jam)", "Audit log filterable"], tips: ["Simpan API key di Settings, BUKAN di .env jika perlu diubah dari UI.", "Jangan hapus/downgrade admin terakhir.", "Audit log membantu tahu siapa yang mengubah data."] } },
  { id: "reports", title: "Laporan & Analitik", category: "System", icon: <FileText size={16} />, content: { apa: "Halaman ringkasan performa bisnis: conversion funnel, revenue trend, dan lead source analytics.", cara: ["Buka /reports dari sidebar", "Lihat overview: total leads, conversion rate, revenue", "Filter berdasarkan periode", "Export data jika diperlukan"], fitur: ["Conversion funnel visualization", "Lead source breakdown", "Revenue per service type", "Period comparison"] } },
  { id: "tasks", title: "Background Tasks", category: "System", icon: <Settings size={16} />, content: { apa: "Monitor background jobs yang sedang berjalan: scraping, AI analysis, follow-up scheduler, blast queue.", cara: ["Buka /tasks dari sidebar", "Lihat daftar task yang running/completed/failed", "Klik task untuk detail + error log", "Retry failed tasks jika diperlukan"], fitur: ["Real-time status update", "Error log per task", "Auto-cleanup completed tasks setelah 24 jam"] } },
  { id: "roles", title: "HCM MVP: Role & Akses", category: "System", icon: <Users size={16} />, content: { apa: "Sistem akun tim sederhana. Admin punya akses penuh, Member dipakai untuk tim operasional agar setiap aksi punya pemilik dan tidak semua orang memakai akun admin.", cara: ["Admin buka Settings → Tim & Role", "Buat akun member dengan nama, email, password awal, dan role", "Member login dengan akun sendiri", "Admin bisa edit role, reset password, atau hapus user jika bukan akun sendiri"], fitur: ["Admin: akses penuh termasuk settings, data admin, user, dan aksi sensitif", "Member: fokus operasional seperti leads, clients, board, workspace, dan dokumen sesuai menu yang tersedia", "Tidak bisa menghapus akun sendiri", "Tidak bisa menghapus atau menurunkan role admin terakhir", "Setiap aksi penting dapat dicatat di Audit Log"], tips: ["Buat akun member untuk tim SEO, content, admin sales, atau finance agar kerja tidak bercampur.", "Untuk MVP belum ada permission granular per fitur; role granular bisa ditambah setelah pola kerja tim sudah jelas."] } },
];

export interface PipelineStage {
  id: string; label: string; sub: string; Icon: LucideIcon;
  colorClass: string; bgClass: string; borderClass: string;
  trigger: string; output: string; ai: string; manual: string;
  flow: string; nextHint: string;
  badge: string | null; link: string;
}

export const PIPELINE_STAGES: PipelineStage[] = [
  { id: "scrape", label: "Scrape", sub: "Google Maps", Icon: Search, colorClass: "text-blue-500", bgClass: "bg-blue-500/10", borderClass: "border-blue-500/30", trigger: "Manual — admin pilih kategori + kota di Maps Scraper", output: "Leads baru: nama bisnis, nomor WA, alamat, rating Google", ai: "Auto-score 40–85 berdasarkan rating, ada/tidaknya website, jumlah review", manual: "Pilih kategori, lokasi, max results, product interest", flow: "Mulai dari sini saat butuh prospek baru. Pilih kategori bisnis (mis. 'klinik gigi') + kota target, sistem scrape Google Maps → simpan ke daftar Leads. Setiap lead langsung dapat skor AI awal.", nextHint: "Lanjut ke Leads untuk filter & kelola hasil scrape.", badge: null, link: "/scraper" },
  { id: "leads", label: "Leads", sub: "CRM Pipeline", Icon: Users, colorClass: "text-purple-500", bgClass: "bg-purple-500/10", borderClass: "border-purple-500/30", trigger: "Auto dari scraper atau input manual", output: "Lead dengan status: Scraped → Contacted → HOT_PROSPECT → Closed/Client", ai: "Lead scoring otomatis + AI analysis (pain points, suggested product)", manual: "Update status, rating, product interest", flow: "Tahap kurasi. Filter lead skor tinggi (≥80 = Siap Closing), baca pain points hasil AI, tandai produk yang relevan. Lead yang sudah 'matang' dikirim WA Blast atau langsung dibuatkan proposal.", nextHint: "Cold lead → kirim WA Blast atau Audit Report dulu. Warm lead → langsung Proposal.", badge: "Auto-score", link: "/contacts" },
  { id: "blast", label: "Blast WA", sub: "Fonnte API", Icon: Send, colorClass: "text-green-500", bgClass: "bg-green-500/10", borderClass: "border-green-500/30", trigger: "Manual — admin pilih template + filter leads", output: "WA terkirim dengan link report publik, status → BLASTED", ai: "Template personalisasi {{business_name}}, {{proposal_link}}", manual: "Pilih template, filter leads, klik blast", flow: "Outreach awal. Pilih segmen lead, pilih template (variabel auto-isi nama bisnis), kirim. Sistem track delivery, read, dan reply. Lead yang reply pindah otomatis ke status REPLIED. Followup sequence auto-stop kalau lead sudah balas.", nextHint: "Yang buka Audit Report = sinyal hangat → siapkan Proposal.", badge: "Followup auto", link: "/marketing/blast-analytics" },
  { id: "report", label: "Report", sub: "Halaman Publik", Icon: FileText, colorClass: "text-orange-500", bgClass: "bg-orange-500/10", borderClass: "border-orange-500/30", trigger: "Lead klik link report di pesan WA", output: "Lead score naik, status → REPORT_VIEWED → HOT_PROSPECT", ai: "Pain Box, ROI Slider, FOMO Timer 24 jam, Ghost Viewer detection", manual: "Tidak ada — fully automated tracking", flow: "Hook value sebelum jual. Audit digital singkat untuk lead cold yang belum kenal. Semua engagement (durasi baca, scroll depth) seringkas. Skor lead naik otomatis kalau report dibuka.", nextHint: "Setelah report dibuka 1–2 kali, lanjut ke Proposal.", badge: "Ghost viewer", link: "/proposals" },
  { id: "proposal", label: "Proposal", sub: "Multi-service", Icon: ClipboardList, colorClass: "text-amber-500", bgClass: "bg-amber-500/10", borderClass: "border-amber-500/30", trigger: "Admin buat proposal dari halaman Klien", output: "Link publik /p/{slug} + analytics waktu baca per section", ai: "Auto-detect service type, contract months, nama project", manual: "Pilih layanan, set harga, kirim link ke prospect", flow: "Penawaran resmi. Dua jalur: (1) Proposal interaktif dengan tombol Accept — klien klik, sistem auto-create Project + Board + Workspace. (2) Surat penawaran legal manual — generate PDF dari Document Generator, tanda tangan, lalu admin buat workspace manual setelah deal.", nextHint: "Klien Accept → otomatis lompat ke tahap Close. Manual deal → buat project di /clients sendiri.", badge: "2 jalur", link: "/proposals" },
  { id: "close", label: "Close", sub: "Accept → Project", Icon: CheckCircle2, colorClass: "text-red-500", bgClass: "bg-red-500/10", borderClass: "border-red-500/30", trigger: "Klien klik Accept di halaman proposal publik", output: "Contact + Project + Board kanban auto-created", ai: "Auto-detect project type, service type, contract months", manual: "Tidak ada — fully automated saat accept", flow: "Titik konversi. Begitu klien Accept, sistem buat Contact (klien), Project (FIXED/RETAINER), Board kanban kosong, dan Workspace dari template service_type. Admin dapat notifikasi WA. Tidak perlu klik apapun.", nextHint: "Setelah ini langsung ke Board / Workspace untuk eksekusi.", badge: "Auto-project", link: "/clients" },
  { id: "board", label: "Board", sub: "Kanban", Icon: LayoutGrid, colorClass: "text-indigo-500", bgClass: "bg-indigo-500/10", borderClass: "border-indigo-500/30", trigger: "Auto-created saat proposal accepted", output: "Board kanban: To Do, In Progress, Review, Done", ai: "Tidak wajib AI; fokus ke tracking visual dan sinkron Workspace", manual: "Drag & drop card, assign, due date, checklist, komentar, attachment", flow: "Eksekusi visual ala Trello. Board menunjukkan status cepat, sementara detail SOP dan bukti kerja tetap di Workspace. Card yang linked ke Workspace ikut pindah Done saat task selesai.", nextHint: "Detail data per task → buka Workspace sheet.", badge: "Kanban", link: "/board" },
  { id: "deliver", label: "Deliver", sub: "Workspace + Docs", Icon: Package, colorClass: "text-teal-500", bgClass: "bg-teal-500/10", borderClass: "border-teal-500/30", trigger: "Project aktif", output: "Spreadsheet workspace, dokumen (invoice, kontrak, proposal PDF)", ai: "Generator konten fokus Artikel SEO jika layanan butuh konten", manual: "Isi workspace, upload bukti, generate dokumen, kirim ke klien", flow: "Pengerjaan harian. Workspace = SOP detail per project: tahap, PIC, deadline, output/link bukti, dan kriteria selesai. Tandai task milestone 'Invoice pembayaran X%' jadi Done → modal auto-generate invoice. Dokumen lain dibuat dari Document Generator pakai brand kit.", nextHint: "Project selesai → invoice final → masuk fase Retain (atau archive).", badge: null, link: "/workspace" },
  { id: "retain", label: "Retain", sub: "Followup + Invoice", Icon: RefreshCw, colorClass: "text-emerald-500", bgClass: "bg-emerald-500/10", borderClass: "border-emerald-500/30", trigger: "Project aktif + followup_enabled=true", output: "WA followup otomatis, invoice bulanan, upsell pipeline", ai: "AI Chat business partner untuk analisis retensi & upsell", manual: "Enable followup di Settings, input data finance", flow: "Pasca-deal. Untuk retainer: invoice tiap bulan, followup WA otomatis ke klien tidak aktif, AI Chat dipakai untuk analisis kesehatan akun & saran upsell. Loop balik ke Proposal kalau ada layanan tambahan.", nextHint: "Klien butuh layanan baru → balik ke tahap Proposal.", badge: "Auto-invoice", link: "/finance" },
];

export const AI_FEATURES = [
  { name: "Chat", sub: "Business Partner", feature: "chat", color: "text-amber-500" },
  { name: "Content", sub: "Artikel SEO", feature: "content", color: "text-blue-500" },
  { name: "Analysis", sub: "Lead Insights", feature: "analysis", color: "text-purple-500" },
];
