"""Services package — extracted business logic from routers."""
from app.services.lead_service import (
    search_leads,
    get_leads_with_ghost_viewer_flag,
    update_lead_status,
    recalculate_lead_score,
    recalculate_all_lead_scores,
    export_leads_csv,
)

from app.services.finance_service import (
    get_wallet_balance,
    invalidate_wallet_cache,
    invalidate_all_wallet_cache,
    calculate_financial_summary,
    calculate_expense_by_category,
    create_transaction,
    get_transactions,
)

from app.services.workspace_service import (
    init_workspace_sheets,
    get_workspace_data,
    get_workspace_summary,
    update_cell,
    update_cell_by_row_and_column,
    add_row,
    get_workspace_list_data,
)

from app.services.ai_service import (
    get_default_model,
    get_ai_config,
    get_proxy_for_feature,
    call_ai_sync,
    build_analysis_prompt,
    parse_ai_response,
    build_caption_system_message,
    parse_caption_response,
    parse_seo_article_response,
    generate_caption,
    generate_seo_article,
    list_content_providers,
    create_content_provider,
    update_content_provider,
    delete_content_provider,
    list_ai_proxies,
    create_ai_proxy,
    update_ai_proxy,
    activate_ai_proxy,
    delete_ai_proxy,
    _get_feature_defaults,
    set_feature_defaults,
)

from app.services.board_service import (
    create_board_column,
    update_board_column,
    delete_board_column,
    create_board_card,
    get_board_card,
    update_board_card,
    delete_board_card,
    move_board_card,
    create_card_comment,
    create_card_checklist,
    toggle_checklist_item,
    delete_checklist_item,
    card_to_out,
)

from app.services.document_service import (
    _get_active_kit,
    serialize_brand_kit,
    build_brand_context,
    get_document_template_type,
    document_template_starter,
    _serialize_template,
    _next_doc_sequence,
    _peek_doc_sequence,
    _generate_document_filename,
    _slugify_name,
    _DOC_TYPE_PREFIX,
    render_document_html,
    visible_text_from_html,
    inject_pdf_font,
    _build_default_vars,
    generate_document_pdf,
    list_templates,
    create_document_template,
    update_document_template,
    delete_document_template,
    get_invoice_sequence,
    set_invoice_sequence,
)

from app.services.proposal_service import (
    generate_proposal_slug,
    detect_project_type,
    detect_service_type,
    months_between_dates,
    detect_contract_months,
    build_roi_data,
    create_proposal,
    proposal_to_out,
    get_proposal_templates,
    get_timeline_templates,
    log_proposal_open,
    log_proposal_ping,
    log_proposal_duration,
    get_proposal_analytics,
    accept_proposal,
    reject_proposal,
)

from app.services.archive_service import (
    list_archive_folders,
    create_archive_folder,
    update_archive_folder,
    delete_archive_folder,
    parent_creates_cycle,
    list_archive_docs,
    get_archive_doc,
    create_archive_doc,
    update_archive_doc,
    delete_archive_doc,
)

from app.services.campaign_service import (
    log_outreach_cost,
    log_ai_cost,
    get_template_stats,
    create_blast_campaign,
    list_blast_campaigns,
    get_blast_campaign,
    cancel_blast_campaign,
    delete_blast_campaign,
    execute_blast_campaign,
    process_pending_blasts,
    scheduled_followup_processor,
    _analysis_jobs,
    _blast_jobs,
)

from app.services.auth_service import (
    create_jwt_token,
    decode_jwt_token,
    hash_password,
    verify_password,
    encrypt_credential,
    decrypt_credential,
    check_login_rate_limit,
    record_login_failure,
    record_login_success,
    authenticate_user,
    mask_secret,
    is_sensitive_key,
)
