export const INDONESIA_LOCATION_PRESETS: Record<string, string[]> = {
  Aceh: ["Banda Aceh", "Sabang", "Langsa", "Lhokseumawe", "Subulussalam", "Aceh Besar", "Pidie", "Bireuen", "Aceh Utara", "Aceh Tengah"],
  "Sumatera Utara": ["Medan", "Binjai", "Tebing Tinggi", "Pematangsiantar", "Tanjungbalai", "Sibolga", "Padangsidimpuan", "Deli Serdang", "Karo", "Asahan"],
  "Sumatera Barat": ["Padang", "Bukittinggi", "Payakumbuh", "Pariaman", "Solok", "Sawahlunto", "Padang Panjang", "Agam", "Tanah Datar", "Pesisir Selatan"],
  Riau: ["Pekanbaru", "Dumai", "Siak", "Kampar", "Bengkalis", "Rokan Hulu", "Rokan Hilir", "Indragiri Hulu", "Indragiri Hilir", "Pelalawan"],
  "Kepulauan Riau": ["Batam", "Tanjungpinang", "Bintan", "Karimun", "Natuna", "Lingga", "Anambas"],
  Jambi: ["Jambi", "Sungai Penuh", "Muaro Jambi", "Batanghari", "Bungo", "Tebo", "Merangin", "Sarolangun", "Tanjung Jabung Barat", "Tanjung Jabung Timur"],
  Bengkulu: ["Bengkulu", "Rejang Lebong", "Kepahiang", "Lebong", "Bengkulu Utara", "Bengkulu Selatan", "Seluma", "Kaur", "Mukomuko"],
  "Sumatera Selatan": ["Palembang", "Prabumulih", "Pagar Alam", "Lubuklinggau", "Banyuasin", "Ogan Ilir", "Ogan Komering Ilir", "Muara Enim", "Musi Banyuasin", "Lahat"],
  "Bangka Belitung": ["Pangkalpinang", "Bangka", "Bangka Barat", "Bangka Tengah", "Bangka Selatan", "Belitung", "Belitung Timur"],
  Lampung: ["Bandar Lampung", "Metro", "Lampung Selatan", "Lampung Tengah", "Lampung Timur", "Lampung Utara", "Pesawaran", "Pringsewu", "Tanggamus", "Way Kanan"],
  Banten: ["Tangerang", "Tangerang Selatan", "Serang", "Cilegon", "Pandeglang", "Lebak", "Kabupaten Tangerang", "Kabupaten Serang"],
  "DKI Jakarta": ["Jakarta Selatan", "Jakarta Barat", "Jakarta Pusat", "Jakarta Timur", "Jakarta Utara", "Kepulauan Seribu"],
  "Jawa Barat": ["Bandung", "Bekasi", "Bogor", "Depok", "Cimahi", "Cirebon", "Sukabumi", "Tasikmalaya", "Banjar", "Garut", "Karawang", "Purwakarta", "Subang"],
  "Jawa Tengah": ["Semarang", "Surakarta", "Magelang", "Tegal", "Pekalongan", "Salatiga", "Purwokerto", "Cilacap", "Kudus", "Jepara", "Pati", "Klaten", "Sukoharjo"],
  "DI Yogyakarta": ["Yogyakarta", "Sleman", "Bantul", "Kulon Progo", "Gunungkidul"],
  "Jawa Timur": ["Surabaya", "Malang", "Sidoarjo", "Gresik", "Kediri", "Madiun", "Blitar", "Pasuruan", "Probolinggo", "Batu", "Jember", "Banyuwangi", "Mojokerto"],
  Bali: ["Denpasar", "Badung", "Gianyar", "Tabanan", "Buleleng", "Karangasem", "Klungkung", "Bangli", "Jembrana"],
  "Nusa Tenggara Barat": ["Mataram", "Lombok Barat", "Lombok Tengah", "Lombok Timur", "Lombok Utara", "Sumbawa", "Sumbawa Barat", "Bima", "Dompu"],
  "Nusa Tenggara Timur": ["Kupang", "Ende", "Maumere", "Labuan Bajo", "Manggarai", "Manggarai Barat", "Sikka", "Flores Timur", "Sumba Timur", "Belu"],
  "Kalimantan Barat": ["Pontianak", "Singkawang", "Kubu Raya", "Mempawah", "Sambas", "Ketapang", "Sintang", "Sanggau", "Landak", "Bengkayang"],
  "Kalimantan Tengah": ["Palangka Raya", "Kotawaringin Barat", "Kotawaringin Timur", "Kapuas", "Pulang Pisau", "Barito Selatan", "Barito Utara", "Gunung Mas", "Katingan"],
  "Kalimantan Selatan": ["Banjarmasin", "Banjarbaru", "Banjar", "Barito Kuala", "Tanah Laut", "Tanah Bumbu", "Kotabaru", "Hulu Sungai Selatan", "Tabalong"],
  "Kalimantan Timur": ["Samarinda", "Balikpapan", "Bontang", "Kutai Kartanegara", "Kutai Timur", "Kutai Barat", "Berau", "Paser", "Penajam Paser Utara"],
  "Kalimantan Utara": ["Tarakan", "Tanjung Selor", "Nunukan", "Malinau", "Bulungan", "Tana Tidung"],
  "Sulawesi Utara": ["Manado", "Bitung", "Tomohon", "Kotamobagu", "Minahasa", "Minahasa Utara", "Minahasa Selatan", "Bolaang Mongondow"],
  Gorontalo: ["Gorontalo", "Bone Bolango", "Gorontalo Utara", "Boalemo", "Pohuwato", "Kabupaten Gorontalo"],
  "Sulawesi Tengah": ["Palu", "Donggala", "Sigi", "Parigi Moutong", "Poso", "Tojo Una-Una", "Banggai", "Morowali", "Tolitoli"],
  "Sulawesi Barat": ["Mamuju", "Majene", "Polewali Mandar", "Mamasa", "Pasangkayu", "Mamuju Tengah"],
  "Sulawesi Selatan": ["Makassar", "Parepare", "Palopo", "Gowa", "Maros", "Takalar", "Jeneponto", "Bulukumba", "Bone", "Wajo", "Pinrang", "Tana Toraja"],
  "Sulawesi Tenggara": ["Kendari", "Baubau", "Kolaka", "Kolaka Utara", "Kolaka Timur", "Konawe", "Konawe Selatan", "Muna", "Buton", "Wakatobi"],
  Maluku: ["Ambon", "Tual", "Maluku Tengah", "Seram Bagian Barat", "Seram Bagian Timur", "Buru", "Buru Selatan", "Kepulauan Aru"],
  "Maluku Utara": ["Ternate", "Tidore Kepulauan", "Halmahera Barat", "Halmahera Selatan", "Halmahera Utara", "Halmahera Timur", "Kepulauan Sula"],
  "Papua Barat": ["Manokwari", "Fakfak", "Kaimana", "Teluk Bintuni", "Teluk Wondama", "Pegunungan Arfak"],
  "Papua Barat Daya": ["Sorong", "Raja Ampat", "Sorong Selatan", "Maybrat", "Tambrauw"],
  Papua: ["Jayapura", "Sarmi", "Keerom", "Mamberamo Raya", "Kepulauan Yapen", "Biak Numfor", "Supiori", "Waropen"],
  "Papua Tengah": ["Nabire", "Mimika", "Paniai", "Dogiyai", "Deiyai", "Intan Jaya", "Puncak", "Puncak Jaya"],
  "Papua Pegunungan": ["Jayawijaya", "Wamena", "Yahukimo", "Tolikara", "Lanny Jaya", "Nduga", "Mamberamo Tengah", "Yalimo"],
  "Papua Selatan": ["Merauke", "Asmat", "Boven Digoel", "Mappi"],
};
